/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmichat;

import java.io.File;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick C
 */
public class FramePr extends javax.swing.JFrame {
    
    boolean InitializationVerify = false;
    File fileX = new File("a.txt");
    Registry registry;
    //Registry registry = LocateRegistry.getRegistry(8888);
    //ChatInterface server = (ChatInterface)registry.lookup("ejemplo");
    ChatInterface server;
    /**
     * Creates new form FramePr
     */
    public FramePr() {
        initComponents();
        try {
            registry = LocateRegistry.getRegistry(8888);
            server = (ChatInterface)registry.lookup("ejemplo");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ta_principal = new javax.swing.JTextArea();
        jb_read = new javax.swing.JButton();
        jb_write = new javax.swing.JButton();
        jb_read_file = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ta_principal.setColumns(20);
        ta_principal.setRows(5);
        jScrollPane1.setViewportView(ta_principal);

        jb_read.setText("Init");
        jb_read.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_readMouseClicked(evt);
            }
        });

        jb_write.setText("Escribir");
        jb_write.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_writeMouseClicked(evt);
            }
        });

        jb_read_file.setText("Leer");
        jb_read_file.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_read_fileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jb_read_file)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_write)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jb_read)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_write)
                    .addComponent(jb_read_file))
                .addGap(13, 13, 13)
                .addComponent(jb_read))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_readMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_readMouseClicked
        // TODO add your handling code here:
        try{
            if (!InitializationVerify) {
                InitializationVerify = true;
                System.out.println("Nombre:");
                String name = JOptionPane.showInputDialog(this, "Nombre");

                ChatInterface client = new Chat(name, fileX);
                String msg = "[" + client.getName() + "] conectado!";
                server.send(msg);
                System.out.println("Servicio listo");
                server.setClient(name, client);
                String user = "";
            } else {
                JOptionPane.showMessageDialog(this, "Already logged in");
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_readMouseClicked

    private void jb_read_fileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_read_fileMouseClicked
        // TODO add your handling code here:
        try {
            if (InitializationVerify) {
                String getMessageData = server.leerArchivo();
                ta_principal.setText(getMessageData);
            }else{
                JOptionPane.showMessageDialog(this, "Access Denied. Init the client connection");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_read_fileMouseClicked

    private void jb_writeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_writeMouseClicked
        // TODO add your handling code here:
        try {
            if(InitializationVerify){
                String data = ta_principal.getText();
                server.escribirArchivo(data);
            }else{
                JOptionPane.showMessageDialog(this, "Access Denied. Init the client connection");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_writeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_read;
    private javax.swing.JButton jb_read_file;
    private javax.swing.JButton jb_write;
    private javax.swing.JTextArea ta_principal;
    // End of variables declaration//GEN-END:variables
}
